### ISSUE TITLE
skip failure_app callback

### ISSUE THREAD

**Issue by vladislav-zubov** [wardencommunity/warden#100]
Hello. Sorry for my english. I wrote API for my application and I ran into a problem. My Api wrote on **Grape**:

``` ruby
# api.rb
class API < Grape::API
  ...
  helpers do
    def authenticate!
      if current_user
        ...
      else
        error!('Unauthorized. Invalid or expired token.', 401)
      end
    end
  end
  ....
end
```

**authenticate!** method is called whenever I advert to api.
My warden configuration:

``` ruby
Rails.application.config.middleware.use Warden::Manager do |manager|
  manager.default_strategies :password
  manager.failure_app = lambda { |env| SessionsController.action(:new).call(env) }
end
```

when the user is not authorized.. calls **error!** method in which I pass the 401 error code thereby **failure_app** block called. Can I skip this block? 
I was trying to pass any other error code, and it works well. But I need to pass the error code 401.

**Comment by jsmestad** [comment]
For those that find this, we now have this in the README on [hassox/rails_warden](https://github.com/hassox/rails_warden)
