### ISSUE TITLE
Incomplete sessions hash

### ISSUE THREAD

**Issue by ThomasAlxDmy** [wardencommunity/warden#109]
Hey guys,

I recently run into some issue and I have no idea how this could even happen.
For some reason my model name is not part of the session hash: 

{"session_id"=>"e7b4039f457a9bdab4f5aa435f8c7234", "warden.user.user.key"=>[[1], nil], "_csrf_token"=>"S79Q6uhLVziFj2VpHa+r6J3lQIz4GC881XX4="}

Obviously that causes my application to crash. Any idea of what could have happen?

**Comment by hassox** [comment]
Without looking at the serializer for your setup, there's no way to tell what's happening
