### ISSUE TITLE
`Warden::Proxy` access response in callback

### ISSUE THREAD

**Issue by bradrobertson** [wardencommunity/warden#135]
[These docs](https://github.com/hassox/warden/wiki/Callbacks#example-3) seem to suggest that the warden proxy passed to the block when the callback is run has a `response` object on it, that you can then do things like modify cookies on.

eg:

``` ruby
Warden::Manager.before_logout do |user,auth,opts|
  auth.response.delete_cookie "remember_token"
end
```

I can't for the life of me see any reference to a response object within that proxy class. Is this wiki up to date? Assuming I'm right and there is no response object, how would one go about setting / deleting a cookie from a callback (eg `after_set_user`).

We're currently using the rails cookie jar, but we're trying to remove the rails dependency which is proving harder than anticipated as we can't see how we can modify the rack response anywhere in this hook.

**Comment by ginjo** [comment]
Ditto here, trying to manipulate the response object exactly per the wiki, however...

`undefined method `response' for #<Warden::Proxy:0x000001009f8cc8>`

**Comment by GabrielLagos** [comment]
closed? What was the resolution on this? We are currently seeing the same issue. I'm assuming we're doing something wrong but a hint would be nice.

**Comment by linhdangduy** [comment]
> how would one go about setting / deleting a cookie from a callback (eg after_set_user).

this is what I'm finding now. Any ideas?

**Comment by linhdangduy** [comment]
Oh, just found this from stackoverflow post
```ruby
Warden::Manager.after_set_user except: :fetch do |user, auth, opts|
  ## play with cookies by auth param
  auth.cookies[:example]
end
```
