### ISSUE TITLE
CI Status Never Reported

### ISSUE THREAD

**Issue by landongrindheim** [wardencommunity/warden#176]
I noticed that CI build statuses are not being reported for this repository. Did a little investigation and found that this is something that's been around for a bit.

Per https://github.com/travis-ci/travis-ci/issues/10204
> those repositories on travis-ci.com which are managed by GitHub Apps no longer receive updates to the GitHub Commit Status API. Instead, Build Statuses will be posted to the GitHub Check Runs API.

Is this something that's potentially affecting this repo? If so, the [issue](https://github.com/travis-ci/travis-ci/issues/10204) referenced above also lays out the steps that can be taken to resolve this.
> To fix this issue, update your repositories using protected branches to require GitHub Checks as follows:
> 1. Go to the repository’s Branch Settings page (https://github.com/OWNER/REPO/settings/branches).
> 2. In the "Branch Protection Settings" section, click "Edit" for a protected branch
> 3. Scroll down to the second box, "Require status checks to pass before merging." Select either "Travis CI - Pull Request" or "Travis CI - Branch" or both. (Note: "continuous-integration/travis-ci" is the Status API event which is deprecated)
> 4. Save your changes

**Comment by jsmestad** [comment]
I will toss this on my TODO list. Should be able to fix this next week.

Thanks for reporting :)
