### ISSUE TITLE
Problem with Rack::Flash and Failure App

### ISSUE THREAD

**Issue by resistorsoftware** [wardencommunity/warden#18]
Hi,

I am seeing my Failure App get called. Inside that call which receives the env, I see my Rack::Flash variables. I set the Flash up to contain the error from my login code... but it seems that when I redirect back into my App, the Rack environment is completely new and reset?

```
class FailureApp
    def call(env)
      env['x-rack.flash'][:notice] = env['warden'].message unless env['x-rack.flash'].nil?
      [302, {'Location' => env['warden.options'][:attempted_path], 'Content-type' => 'text/html'},'']
    end
end
```

Sure enough, when I examine the env in my App, there is no @notice it is nil...

How can I maintain my use of the Flash structure? Why does it get cleaned out and reset?

Any tips most appreciated.

Thanks

Nevermind, I figured it out...

**Comment by raquelhortab** [comment]
@resistorsoftware could you explain why you closed this? Did you solve it? I have kind of a similar problem. I'm trying, after a user failed to log in, to try and log them in using another model, same credentials. Flash is lost between the two calls o authenticate! and that makes everything crash.
