### ISSUE TITLE
`login_as` not working with Puma 4.3.2

### ISSUE THREAD

**Issue by kaspernj** [wardencommunity/warden#183]
Dependabot suggested upgrading to Puma 4.3.2 because of a security fix.

It looks like after upgrading `login_as` has stopped working in my integration / system specs. `current_user` is nil in my tests at least, even though I expected a user to be present because I am using `login_as`. If I spin up my app in development mode everything works fine, so it is only while testing.

The description of the security fix is: `Fix: Prevent HTTP Response splitting via CR/LF in header values.`

**Comment by jcope2013** [comment]
Upgrade to Puma 4.3.3 

https://github.com/puma/puma/blob/master/History.md

**Comment by kaspernj** [comment]
That worked. Thanks :-)
