### ISSUE TITLE
Gem Release?

### ISSUE THREAD

**Issue by philipbjorge** [wardencommunity/warden#192]
Hi there!

We've been pinned to version 1.2.7 of Warden since... early 2019.
It looks like the blocking issue was fixed for our team in July 2019...
https://github.com/wardencommunity/warden/issues/171

Do you know when the next release of this gem is planned?

Thanks for all the great work on Warden!

**Comment by jsmestad** [comment]
Yeah I can take a crack at this in the next week. Please remind me if I miss that goal 👍

**Comment by jsmestad** [comment]
Alright I have pushed `v1.2.9` 🎉 

Let me know how it works for you

**Comment by philipbjorge** [comment]
@jsmestad -- Thanks so much for cutting this release!
We'll upgrade to this shortly :smiley: :partying_face: !
