### ISSUE TITLE
Callback before_logout not called when logging out

### ISSUE THREAD

**Issue by Jazzatola** [wardencommunity/warden#76]
Hi

I'm currently working on a sinatra application using Warden for authentication. I've noticed that when calling `env['warden'].logout` the `before_logout` callback is not being executed. If I change it to `env['warden'].logout(:default)` then the callback is executed but fails as I'm not explicitly using any scopes and the user passed in is `nil`.

This is the first time I've used Warden so I'm hoping its just something simple that I've done wrong but it would be good to know what the problem is.

I've put together a small example application to demonstrate the problem: https://gist.github.com/Jazzatola/5685517

**Comment by badosu** [comment]
I had the same problem. Since this issue was closed I assume this was fixed or accepted as a design feature?
