### ISSUE TITLE
Does warden clear the session after authenticating?

### ISSUE THREAD

**Issue by agis** [wardencommunity/warden#94]
I've noticed that each time a user authenticates, the session_id changes. Is this expected behavior?

I'm using Rails.

**Comment by hariharan-ally** [comment]
Can someone point me to the exact code in Warden which does this? Will help me debug an issue. @hassox  @agis @azul @olleolleolle @EdwardBetts Thanks in advance!

**Comment by mvz** [comment]
@hariharan-ally I think it happens here: https://github.com/wardencommunity/warden/blob/88d2f59adf5d650238c1e93072635196aea432dc/lib/warden/proxy.rb#L181-L185

The 'renew' option gets picked op by the Rack session middleware. See here: https://github.com/rack/rack-session/blob/d2f080c243cac167fc5176c5cf869e23fe7f6ec6/lib/rack/session/abstract/id.rb#L223
